workspace:
  base: workspace
pipeline:
  scp:
    image: appleboy/drone-scp
    host: vps135621.vps.ovh.ca
    username: root
    password: Cj57AQCn
    port: 22
    target: /home/hheyomar16
    source: /home/ubuntu/mysql.tar.gz