pipeline:
  backup-mysql-data:
    image: alpine
    commands:
      - apk update && apk add --no-cache openssh sshpass
      - export SSHPASS=Cj57AQCn
      - sshpass -e ssh -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca 'rm -rf mysql.tar.gz;tar -czvf /home/ubuntu/mysql.tar.gz /home/ubuntu/ambientes/dev/data/mysql'
  copying-mysql-data:
    image: alpine
    commands:
      - apk update && apk add --no-cache openssh sshpass
      - cd /workspace
      - export SSHPASS=Cj57AQCn
      - sshpass -e scp -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca:/home/ubuntu/mysql.tar.gz mysql.tar.gz 
      - tar -xzvf mysql.tar.gz
      - mv mysql mysql-v
      - mv mysql-v/* .
      - ls
      - sshpass -e ssh -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca 'rm -rf /home/ubuntu/mysql.tar.gz'
    volumes:
      - worskpace-drone:/workspace
  mysql:
   image: mysql:5.7
   volumes:
      - worskpace-drone:/var/lib/mysql
   detach: true
  liquibase-changes:
    image: sequenceiq/liquibase
    environment:
      - CONNECTION_STRING=jdbc:mysql://mysql:3306/GtwHatcc?useUnicode=true&characterEncoding=utf8&useSSL=false
      - DB_USER=root
      - DB_PASS=Cj57AQCn




docker run -it \
--name $LIQUIBASE_CONTAINER \
--link $REFERENCE_DB_CONTAINER:db \
--entrypoint="/scripts/liquibase_command.sh" \
-e CONNECTION_STRING="jdbc:postgresql://$DB_IP:5432/$DB_NAME" \
-e DB_USER="$DB_USER" \
-e DB_PASS="$DB_PASS" \
-e LIQUIBASE_INCLUSION_FILE="$LIQUIBASE_INCLUSION_FILE" \
-v /$LIQUIBASE_CHANGELOGS:/changelogs \
sequenceiq/docker-liquibase \
"diff"
The variables should be set as follows:

LIQUIBASE_CONTAINER - the name of the docker container
REFERENCE_DB_CONTAINER - the docker container running a (postgres) database being the reference of the diff command
CONNECTION_STRING - the connection to the target database
DB_IP - the IP address of the target database
DB_NAME - the target database name
DB_USER - the user to the target database
DB_PASS - password to the target database
LIQUIBASE_INCLUSION_FILE - changelog file name in the changelogs folder, the generated diff file will be added as an include tag to it if provided
LIQUIBASE_CHANGELOGS - volume on the host machine, where the generated file will be written
  
  #APLICAR CAMBIOS LIQUIBASE
  # - Sincronizar cambios en los archvivos con esta base de datos
  # - Luego correr aplicacion ( siguiente step )
  # - En caso de pasar encontrar las diferencias entre bases de datos
  # -  VERIFICAR PARA MI SOLO SI COINCIDE CON LOS CAMBIOS QUE SE HICIERON --> No necesario por el momento jeje
  #starting-ms-gateway:
  #   image: hgarcio/gtwhatcc
  #   environment:
  #     - profile=drone
  #running-tests:
  #   image: alpine
  #   commands:
  #    - echo "Correre unas llamadas a las API jeje"
  #CORRER ALGUNOS TEST : crear algun contenedor que haga algunas llamadas a las API si funca todo fresh

    #host: vps135621.vps.ovh.ca
    #username: root
    #password: Cj57AQCn
    ##port: 22
    #target: /home/hheyomar16
    #source: /home/ubuntu/mysql.tar.gz