workspace:
  base: /workspace
pipeline:
  copying-volume:
    image: alpine
    commands:
      - apk update && apk add --no-cache openssh sshpass
      - cd /workspace
      - export SSHPASS=Cj57AQCn
      - sshpass -e scp -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca:/home/ubuntu/mysql.tar.gz mysql.tar.gz 
      - tar -xzvf mysql.tar.gz
  mysql:
    image: mysql:5.7
    detach: true
    volumes:
      - /workspace/mysql:/var/lib/mysql
    #host: vps135621.vps.ovh.ca
    #username: root
    #password: Cj57AQCn
    ##port: 22
    #target: /home/hheyomar16
    #source: /home/ubuntu/mysql.tar.gz