--------------------------------------------------------
--  File created - Thursday-June-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package FLTTYPES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "DADCORPDS"."FLTTYPES" AS
      TYPE "CANALRS" IS REF CURSOR RETURN FLTCANALVIEW%ROWTYPE;
      TYPE "RANGOHORASERVICIOCCRS" IS REF CURSOR RETURN FLTCCSERVICIOSHORAVIEW%ROWTYPE;
      TYPE "RANGOHORACCRS" IS REF CURSOR RETURN FLTRANGOHORARIOCCVIEW%ROWTYPE;
      TYPE "RANGOHORARIORS" IS REF CURSOR RETURN FLTRANGOHORARIOVIEW%ROWTYPE;
      TYPE "RANGOKILOSCCZONARS" IS REF CURSOR RETURN FLTRANGOKILOSCCZONAVIEW%ROWTYPE;
      TYPE "RANGOKILOSRS" IS REF CURSOR RETURN FLTRANGOKILOSVIEW%ROWTYPE;
      TYPE "SERVICIOCCRS" IS REF CURSOR RETURN FLTSERVICIOCCVIEW%ROWTYPE;
      TYPE "SERVICIORS" IS REF CURSOR RETURN FLTSERVICIOVIEW%ROWTYPE;
      TYPE "TRONCALRS" IS REF CURSOR RETURN FLTTRONCALESVIEW%ROWTYPE;
END;


/
