--------------------------------------------------------
--  File created - Thursday-June-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package MNTTYPES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "DADCORPDS"."MNTTYPES" AS
  TYPE "JAULARS"             IS REF CURSOR RETURN "JAULAVIEW"%ROWTYPE;
  TYPE "TRANSPORTISTARS"     IS REF CURSOR RETURN "TRANSPORTISTAVIEW"%ROWTYPE;
  TYPE "CAMIONRS"            IS REF CURSOR RETURN "CAMIONVIEW"%ROWTYPE;
  TYPE "CHOFERRS"            IS REF CURSOR RETURN "CHOFERVIEW"%ROWTYPE;
  TYPE "TIPOORIGENRS"        IS REF CURSOR RETURN "TIPOORIGENVIEW"%ROWTYPE;
  TYPE "ESTADOSDETRS"        IS REF CURSOR RETURN "ESTADOSDETVIEW"%ROWTYPE;
  TYPE "ESTADOSCABRS"        IS REF CURSOR RETURN "ESTADOSCABVIEW"%ROWTYPE;
  TYPE "ZONARS"              IS REF CURSOR RETURN "ZONAVIEW"%ROWTYPE;
  TYPE ZONAPROVEEDORRS       IS REF CURSOR RETURN ZONAPROVEEDORVIEW%ROWTYPE;
  TYPE "TIPOREQUERIMIENTORS" IS REF CURSOR RETURN "TIPOREQUERIMIENTOVIEW"%ROWTYPE;
  TYPE "MOTIVOPOSTVENTARS"   IS REF CURSOR RETURN "MOTIVOPOSTVENTAVIEW"%ROWTYPE;
  TYPE "CENTROCOSTORS"       IS REF CURSOR RETURN "CENTROCOSTOVIEW"%ROWTYPE;
  TYPE "REGIONRS"            IS REF CURSOR RETURN "REGIONVIEW"%ROWTYPE;
  TYPE "CIUDADRS"            IS REF CURSOR RETURN "CIUDADVIEW"%ROWTYPE;
  TYPE "COMUNARS"            IS REF CURSOR RETURN "COMUNAVIEW"%ROWTYPE;
  TYPE "TIENDARS"            IS REF CURSOR RETURN "TIENDAVIEW"%ROWTYPE;
  TYPE "CANALVENTARS"        IS REF CURSOR RETURN "CANALVENTAVIEW"%ROWTYPE;
  TYPE "COMUNAREGIONRS"      IS REF CURSOR RETURN "COMUNAREGIONVIEW"%ROWTYPE;
  TYPE "COMUNAREGIONZONARS"  IS REF CURSOR RETURN "COMUNAREGIONZONAVIEW"%ROWTYPE;
  TYPE "ENVIOPRERUTEORS"     IS REF CURSOR RETURN "ENVIOPRERUTEOVIEW"%ROWTYPE;
  TYPE "MOTIVODEVRS"         IS REF CURSOR RETURN "MOTIVODEVVIEW"%ROWTYPE;
  TYPE "MATRIZCCORIGENRS"    IS REF CURSOR RETURN "MATRIZCCORIGENVIEW"%ROWTYPE;
  TYPE PROVEEDORCCRS         IS REF CURSOR RETURN PROVEEDORCCVIEW%ROWTYPE;
  TYPE "CENTROCOSTOSHORTRS"  IS REF CURSOR RETURN "CENTROCOSTOSHORTVIEW"%ROWTYPE;
  TYPE "COMUNATIEMPORS"      IS REF CURSOR RETURN "COMUNATIEMPOVIEW"%ROWTYPE;
  TYPE "PARAMETROSRS"        IS REF CURSOR RETURN "PARAMETROSVIEW"%ROWTYPE;
  TYPE "CODIGOIATARS"        IS REF CURSOR RETURN "COMUNAREGIONIATAVIEW"%ROWTYPE;
  TYPE "PROVEEDORRS"         IS REF CURSOR RETURN "PROVEEDORESVIEW"%ROWTYPE;
  TYPE "COMUNAZONACCRS"      IS REF CURSOR RETURN "COMUNAZONACCVIEW"%ROWTYPE;
  TYPE COMUNAZONAPROVRS      IS REF CURSOR RETURN COMUNAZONAPROVEEDORVIEW%ROWTYPE;
  TYPE PROVEEDORESPOPURS     IS REF CURSOR RETURN PROVEEDORESPOPUPVIEW%ROWTYPE;
  TYPE "TIPOCCRS"            IS REF CURSOR RETURN "TIPOCCVIEW"%ROWTYPE;
  TYPE "CCTIENDARS"          IS REF CURSOR RETURN "CCTIENDAVIEW"%ROWTYPE;
  TYPE "CCHUADEPTORS"        IS REF CURSOR RETURN "CCHUADEPTOVIEW"%ROWTYPE;
  TYPE "CCHUAPASILLORS"      IS REF CURSOR RETURN "CCHUAPASILLOVIEW"%ROWTYPE;
  TYPE "CCHUALINEALRS"       IS REF CURSOR RETURN "CCHUALINEALVIEW"%ROWTYPE;
  TYPE "CCHUAMETRORS"        IS REF CURSOR RETURN "CCHUAMETROVIEW"%ROWTYPE;
  TYPE "CCCAMIONRS"          IS REF CURSOR RETURN "CCCAMIONVIEW"%ROWTYPE;
  TYPE "RANGOFOLIORS"        IS REF CURSOR RETURN "RANGOFOLIOVIEW"%ROWTYPE;
  TYPE "ESTADORANGOFOLIORS"  IS REF CURSOR RETURN "ESTADORANGOFOLIOVIEW"%ROWTYPE;
  TYPE "EVENTOSDADRS"        IS REF CURSOR RETURN "EVENTOSDADVIEW"%ROWTYPE;
  TYPE "DIASSEMANARS"        IS REF CURSOR RETURN "CCCAPDIASSEMANAVIEW"%ROWTYPE;
  TYPE "RANGOHORARIORS"      IS REF CURSOR RETURN "CCCAPRANGOHORARIOVIEW"%ROWTYPE;
  TYPE "DIASFERIADOSRS"      IS REF CURSOR RETURN "DIASFERIADOSVIEW"%ROWTYPE;
  TYPE "REPORTESDADRS"       IS REF CURSOR RETURN "REPORTESDADVIEW"%ROWTYPE;
  TYPE "CARGATURBORS"        IS REF CURSOR RETURN "EVENTO_LOD"%ROWTYPE;
  TYPE "ZONARANGOHORARS"     IS REF CURSOR RETURN "CCZONARANGOHORAVIEW"%ROWTYPE;
  TYPE "CANALCCCAPACIDADRS"  IS REF CURSOR RETURN "CANALCCCAPACIDADVIEW"%ROWTYPE;
  TYPE "PARAMETROSURIRS"     IS REF CURSOR RETURN "PARAMETROSURIVIEW"%ROWTYPE;
  TYPE "CENTROCOSTONEWRS"    IS REF CURSOR RETURN "CENTROCOSTONEWVIEW"%ROWTYPE;
  TYPE CCTRANSPCAMIONRS      IS REF CURSOR RETURN CCTRANSPORTISTACAMIONVIEW%ROWTYPE;
  TYPE "CENTROCOSENTREGARS"  IS REF CURSOR RETURN "CENTROCOSTOENTREGAVIEW"%ROWTYPE;
  TYPE "AUDIORIALOGRS"       IS REF CURSOR RETURN "AUDITORIAREADVIEW"%ROWTYPE;
  TYPE "GETSINSTOCKRS"       IS REF CURSOR RETURN "SINSTOCKVIEW"%ROWTYPE;
  TYPE CCREGIONALRS          IS REF CURSOR RETURN CCREGIONALVIEW%ROWTYPE;
  TYPE "GETAREARS"           IS REF CURSOR RETURN "GETAREACCOSTOVIEW"%ROWTYPE;
  TYPE "GETAREAORDENRS"      IS REF CURSOR RETURN "GETAREAORDENVIEW"%ROWTYPE;
END;


/
