--------------------------------------------------------
--  File created - Thursday-June-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package PCKTYPES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "DADCORPDS"."PCKTYPES" AS
  TYPE RESERVAPICKINRS          IS REF CURSOR RETURN RESERVAPICKINGVIEW%ROWTYPE;
  TYPE PCKRESERVADETALLERS      IS REF CURSOR RETURN PCKRESERVADETALLEVIEW%ROWTYPE;
  TYPE IMPRESORASRS             IS REF CURSOR RETURN IMPRESORAS%ROWTYPE;
  TYPE FOLIOSRS                 IS REF CURSOR RETURN FOLIOSVIEW%ROWTYPE;
  TYPE RESERVADETALLERS         IS REF CURSOR RETURN PCKRESERVADETALLEPOPUPVIEW%ROWTYPE;
  TYPE RESERVASPRERUTEADAS2RS   IS REF CURSOR RETURN PCKRESERVASPRERUTEADASVIEW2%ROWTYPE;
  TYPE PCKRESERVASRTPORENTREGAR IS REF CURSOR RETURN PCKENTREGACLIENTEVIEW%ROWTYPE;
  TYPE RESERVADETALLEJAULARS    IS REF CURSOR RETURN PCKRESERVADETALLEPOPJAULAVIEW%ROWTYPE;
END;


/
