--------------------------------------------------------
--  File created - Thursday-June-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package PRTTYPES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "DADCORPDS"."PRTTYPES" AS
  TYPE "RESERVAPRTRS" IS REF CURSOR RETURN "RESERVAPRTVIEW"%ROWTYPE;
  TYPE "CCCOMUNAPRTRS" IS REF CURSOR RETURN "CCCOMUNAVIEW"%ROWTYPE;
  TYPE "JAULADISPRS" IS REF CURSOR RETURN "JAULADISPVIEW"%ROWTYPE;
  TYPE "RESERVASPRERUTEADASRS" IS REF CURSOR RETURN "RESERVASPRERUTEADASVIEW"%ROWTYPE;
  TYPE "MOSTRARCONFIRMARHOJARUTARS" IS REF CURSOR RETURN "MOSTRARCONFIRMARHOJARUTAVIEW"%ROWTYPE;
  TYPE "RESERVASPRERUTEADAS2RS" IS REF CURSOR RETURN "RESERVASPRERUTEADASVIEW2"%ROWTYPE;
  TYPE "PRERUTEORS" IS REF CURSOR RETURN "PRERUTEOVIEW"%ROWTYPE;
  TYPE "RESERVASPRERUTEADAS3RS" IS REF CURSOR RETURN "RESERVASPRERUTEADASVIEW3"%ROWTYPE;
  TYPE "RESERVASPRERUTEADAS4RS" IS REF CURSOR RETURN "RESERVASPRERUTEADASVIEW4"%ROWTYPE;
  TYPE "ARCHIVOCURIERRS" IS REF CURSOR RETURN "ARCHIVOCURIERVIEW"%ROWTYPE;
  TYPE "HOJARUTAREIMPRESIONRS" IS REF CURSOR RETURN REIMPRESIONHOJARUTAVIEW%ROWTYPE;
  TYPE "GRIDCOURIERRS" IS REF CURSOR RETURN "GRIDCOURIERVIEW"%ROWTYPE;
  TYPE "ENCUENTRAENJAULARS" IS REF CURSOR RETURN "ENCUENTRAENJAULAVIEW"%ROWTYPE;
  TYPE "CONFIRMARHOJARUTARS" IS REF CURSOR RETURN "HOJARUTAVIEW3"%ROWTYPE;
  TYPE "HRUNIGISVIEWRS" IS REF CURSOR RETURN "HRUNIGISVIEW"%ROWTYPE;
  TYPE "UNIGISFTPVIEWRS" IS REF CURSOR RETURN "UNIGISFTPVIEW"%ROWTYPE;
  TYPE "RESERVASPRERUTEADASLIV2RS" IS REF CURSOR RETURN "RESERVASPRERUTEADASLIVVIEW2"%ROWTYPE;
  TYPE "DETALLEJAULAPRERUTEADASRS" IS REF CURSOR RETURN "DETALLEJAULAPRERUTEADASVIEW"%ROWTYPE;
  TYPE "DETALLEJAULAPRERUTEADAS2RS" IS REF CURSOR RETURN "DETALLEJAULAPRERUTEADAS2VIEW"%ROWTYPE;
  TYPE "RESERVASPRTJAULASELECRS" IS REF CURSOR RETURN "RESERVASPRTJAULASELECVIEW"%ROWTYPE;
  TYPE "REIMPRESIONGDDRS" IS REF CURSOR RETURN REIMPRESIONGDDVIEW%ROWTYPE;
  TYPE "REIMPRESIONGDDDETALLERS" IS REF CURSOR RETURN REIMPRESIONGDDDETALLEVIEW%ROWTYPE;
  TYPE "VALIDARJAULARETIROSRS" IS REF CURSOR RETURN "VALIDARJAULARETIROS"%ROWTYPE;
END;


/
