--------------------------------------------------------
--  File created - Thursday-June-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package RSVTYPES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "DADCORPDS"."RSVTYPES" AS
  TYPE "RESERVARS"               IS REF CURSOR RETURN "RESERVAVIEW"%ROWTYPE;
  TYPE "RESERVARS2"              IS REF CURSOR RETURN "RESERVAVIEW2"%ROWTYPE;
  TYPE "RESERVARS3"              IS REF CURSOR RETURN "RESERVAVIEW3"%ROWTYPE;
  TYPE "RESERVADETALLERS"        IS REF CURSOR RETURN "RESERVADETALLEVIEW"%ROWTYPE;
  TYPE "RESERVADETALLEPROVRS"    IS REF CURSOR RETURN "RESERVADETALLEPROVVIEW"%ROWTYPE;
  TYPE "EVENTOSRS"               IS REF CURSOR RETURN "EVENTOSVIEW"%ROWTYPE;
  TYPE "EVENTOSDETALLERS"        IS REF CURSOR RETURN "EVENTOSDETALLEVIEW"%ROWTYPE;
  TYPE "REQUERIMIENTOSRS"        IS REF CURSOR RETURN "REQUERIMIENTOSVIEW"%ROWTYPE;
  TYPE "TIPOREQUERIMIENTORS"     IS REF CURSOR RETURN "TIPOREQUERIMIENTOVIEW"%ROWTYPE;
  TYPE "RESERVAGESTIONRS"        IS REF CURSOR RETURN "RESERVAGESTIONHDRVIEW"%ROWTYPE;
  TYPE "RESERVAGESTIONDLTRS"     IS REF CURSOR RETURN "RESERVAGESTIONDTLVIEW"%ROWTYPE;
  TYPE "RESERVABIBLIARS"         IS REF CURSOR RETURN "RESERVABIBLIAVIEW"%ROWTYPE;
  TYPE "RESERVASPRIMASRS"        IS REF CURSOR RETURN "RESERVASPRIMASVIEW"%ROWTYPE;
  TYPE "GESTIONPRIMASRS"         IS REF CURSOR RETURN "GESTIONPRIMASVIEW"%ROWTYPE;
  TYPE "GETMINDESPACHORS"        IS REF CURSOR RETURN "GETMINDESPACHOVIEW"%ROWTYPE;
  TYPE "RESERVACAMBIOESTADORS"   IS REF CURSOR RETURN "RESERVACAMBIOESTADOVIEW"%ROWTYPE;
  TYPE "RESERVAESTADOPOSTRS"     IS REF CURSOR RETURN "RESERVAESTADOPOSTVIEW"%ROWTYPE;
  TYPE "RESERVAPOPUPGUIARS"      IS REF CURSOR RETURN "RESERVAPOPUPGUIAVIEW"%ROWTYPE;
  TYPE "RESERVACOURIERRS"        IS REF CURSOR RETURN "RESERVACOURIERVIEW"%ROWTYPE;
  TYPE "COURIERESTADODETRS"      IS REF CURSOR RETURN "COURIERESTADOSDETVIEW"%ROWTYPE;
  TYPE "COURIERTRANSPORTISTARS"  IS REF CURSOR RETURN "COURIERTRANSPORTISTAVIEW"%ROWTYPE;
  TYPE "RESERVAPOPUPDETALLERS"   IS REF CURSOR RETURN "RSVRESERVADETALLEPOPUPVIEW"%ROWTYPE;
  TYPE "RESERVATCKCOURIERRS"     IS REF CURSOR RETURN "RESERVATRACKINGCOURIERVIEW"%ROWTYPE;
  TYPE "MOTIVOANULACIONRS"       IS REF CURSOR RETURN "MOTIVOANULACIONVIEW"%ROWTYPE;
  TYPE "ESTADONCRRS"             IS REF CURSOR RETURN "ESTADONCRVIEW"%ROWTYPE;
  TYPE "ADMREQUERIMIENTOSRS"     IS REF CURSOR RETURN "ADMREQUERIMIENTOSVIEW"%ROWTYPE;
  TYPE "DATOSREQUERIMIENTORS"    IS REF CURSOR RETURN "DATOSREQUERIMIENTOSVIEW"%ROWTYPE;
  TYPE "CAMIONVIGENTERS"         IS REF CURSOR RETURN "CAMIONVIGENTEVIEW"%ROWTYPE;
  TYPE "RESERVAECOMMERCERS"      IS REF CURSOR RETURN "RESERVASECOMMERCEVIEW"%ROWTYPE;
  TYPE "CORREOADMREQRS"          IS REF CURSOR RETURN "CORREOADMREQUERIMIENTOSVIEW"%ROWTYPE;
  TYPE "RESERVASOLICITUDRS"      IS REF CURSOR RETURN "RESERVASOLICITUDVIEW"%ROWTYPE;
  TYPE "RESERVASOLICITUDDESPRS"  IS REF CURSOR RETURN "RESERVASOLICITUDDESPVIEW"%ROWTYPE;

  TYPE "CAPACIDADRS"             IS REF CURSOR RETURN CAPACIDADRESUMENVIEW%ROWTYPE;
  TYPE "CAPACIDADRHRS"           IS REF CURSOR RETURN CAPACIDADRESUMENRHVIEW%ROWTYPE;
  TYPE "CAPACIDADZONARS"         IS REF CURSOR RETURN CAPACIDADRESUMENZONAVIEW%ROWTYPE;
  TYPE "CAPACIDADZONARHRS"       IS REF CURSOR RETURN CAPACIDADRESUMENZONARHVIEW%ROWTYPE;

  TYPE CONSULTARESERVAFINDRS     IS REF CURSOR RETURN CONSULTARESERVAFINDVIEW%ROWTYPE;
  TYPE CONSULTARESERVAGETHDRRS   IS REF CURSOR RETURN CONSULTARESERVAGETHDRVIEW%ROWTYPE;
  TYPE CONSULTARESERVAGETDTLRS   IS REF CURSOR RETURN CONSULTARESERVAGETDTLVIEW%ROWTYPE;
  TYPE CONSULTARESERVAGETVTARS   IS REF CURSOR RETURN CONSULTARESERVAGETVTAVIEW%ROWTYPE;
  TYPE CONSULTARESERVAGETSOLRS   IS REF CURSOR RETURN CONSULTARESERVAGETSOLVIEW%ROWTYPE;

  TYPE INFORMENSRPICKINGRS       IS REF CURSOR RETURN INFORMENSRPICKINGVIEW%ROWTYPE;
  TYPE MONITORPICKINGDTLRS       IS REF CURSOR RETURN MONITORPICKINGDTLVIEW%ROWTYPE;
  TYPE MONITORPICKINGHDRRS       IS REF CURSOR RETURN MONITORPICKINGHDRVIEW%ROWTYPE;
  TYPE INFORMEOTIFRS             IS REF CURSOR RETURN INFORMEOTIFVIEW%ROWTYPE;
  TYPE INFORMEGAPOTIFRS          IS REF CURSOR RETURN INFORMEGAPOTIFVIEW%ROWTYPE;

END;


/
